### ISSUE TITLE
Valor dos honorários advocatícios no final do demonstrativo

### ISSUE THREAD

**Issue by cdandrad** [Contadoria/contadoria.github.io#3]
Não seria interessante constar no final do demonstrativo o valor dos honorários advocatícios (se houver) e já somar esse valor ao TOTAL GERAL?

**Comment by efujit** [comment]
Olá, cdandrad!
Adicionado valor dos honorários no DemonstrativoNovo.
Neste momento, estamos discriminado os valores para expedição do ofício requisitório, que exige o valor total, com principal e juros de mora discriminados. 
O valor dos honorários está sendo apurado separadamente.
Caso haja alguma dúvida, por favor, reabra este issue.
