### ISSUE TITLE
Criando Parecer

### ISSUE THREAD

**Issue by intranet72** [Contadoria/contadoria.github.io#5]
Na atividade 3 não está sendo possível criar o arquivo

**Comment by efujit** [comment]
Olá, @intranet72 .

Para importar dados de uma planilha para um modelo de parecer, recomendamos seguir as orientações do tutorial que segue:
https://contadoria.github.io/Tutoriais/planilha-tc/planilha-rmi/planilha-atrasados/Documento-como-criar-documento-com-dados-das-planilhas/
